pool:
  vmImage: 'ubuntu-latest'

variables:
  node.version: '14.x'
  projectRoot: 'backend'

steps:
  - task: NodeTool@0
    displayName: 'Use Node.js $(node.version)'
    inputs:
      versionSpec: '$(node.version)'

  - script: |
      npm install
    workingDirectory: $(projectRoot)
    displayName: "Install dependencies"
  
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(projectRoot)'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true
  
  - task: AzureWebApp@1
    displayName: 'Deploy Azure Web App'
    inputs:
      azureSubscription: 'mgm-service-connection'
      appType: 'webAppLinux'
      appName: "atc-2024-mgm-be-linux-web-app"
      runtimeStack: 'NODE|14.x'
      package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      startUpCommand: 'npm start'
